---
abstract: 'Catalyst based application'
author:
  - 'Adam Taylor'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wardrobe
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Helper::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Request::Upload: 0
  Catalyst::Runtime: 5.80014
  Catalyst::View::TT: 0
  Config::General: 0
  DBD::SQLite: 0
  Text::CSV_XS: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
