package Wardrobe::Model::WardrobeDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Wardrobe::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:db/wardrobe.db',
        user => '',
        password => '',
    }
);

=head1 NAME

Wardrobe::Model::WardrobeDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Wardrobe>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Wardrobe::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

Adam Taylor

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
